[phases.build]

[custom]
# tambahkan konfigurasi php.ini lewat nginx template
"nginx.template.conf" = '''
http {
  server {
    location ~ \.php$ {
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
      include $!{nginx}/conf/fastcgi_params;
      include $!{nginx}/conf/fastcgi.conf;
      fastcgi_param PHP_VALUE "opcache.enable=1\nopcache.enable_cli=1\nopcache.jit=tracing\nopcache.jit_buffer_size=128M";
    }
  }
}
'''
